---
- name: Create a database on node
  mysql_db:
    login_user: "{{ mysql_root_user }}"
    login_host: "{{ mysql_root_host }}"
    login_password: "{{ mysql_root_password }}"
    name: playground
    state: present
  when : inventory_hostname in groups['master_web_covid']

- name: Insert data on database 
  mysql_query:
    login_user: "{{ mysql_root_user }}"
    login_host: "{{ mysql_root_host }}"
    login_password: "{{ mysql_root_password }}"
    login_db: playground
    query:
      - CREATE TABLE playground.equipment ( id INT NOT NULL AUTO_INCREMENT, type VARCHAR(50), quant INT, color VARCHAR(25), PRIMARY KEY(id))
      - INSERT INTO playground.equipment (type, quant, color) VALUES ("slide", 2, "blue")
  when : inventory_hostname in groups['master_web_covid']

- name: Wait for replication
  pause:
    secondes: 30
    prompt: "Waiting for replication"

- name: check if DB exists
  mysql_query:
    login_user: "{{ mysql_root_user }}"
    login_host: "{{ mysql_root_host }}"
    login_password: "{{ mysql_root_password }}"
    login_db: playground
    query:
      - SELECT * FROM playground.equipment
  register: result_db 

- name: Check if it's created on other nodes
  become: yes
  debug:
    msg:
      - "{{ ansible_default_ipv4.address }} ':'  "
      - "{{ result_db }}"

- name: Remove DB 
  mysql_db:
    login_user: "{{ mysql_root_user }}"
    login_host: "{{ mysql_root_host }}"
    login_password: "{{ mysql_root_password }}"
    name: playground
    state: absent
  when : inventory_hostname in groups['master_web_covid'] 
...