---
- name: Create files on one node 
  become: yes
  file:
    path: /var/www/html/testfile
    state: touch
  when: inventory_hostname in groups['master_web_covid']

- name: Wait for duplication
  pause:
    seconds: 30
    prompt: "Waiting for replication"

- name: Check that the file exists
  stat:
    path: /var/www/html/testfile
  register: stat_result

- name: Debug message if it's exists
  become: yes
  debug:
    msg: "Test file exists on {{ ansible_default_ipv4.address }} "
  when: stat_result.stat.exists

- name: Remove test file 
  become: yes
  file:
    path: /var/www/html/testfile
    state: absent
  when: inventory_hostname in groups['master_web_covid']
...